# Generated by Django 4.2.5 on 2023-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mass',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='XL', max_length=100),
        ),
    ]
