# Generated by Django 4.2.5 on 2023-09-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_mass_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
