# Generated by Django 4.2.5 on 2023-09-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mass',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
