# Generated by Django 4.2.5 on 2023-09-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='trasnport',
            field=models.CharField(default='Поездом', max_length=200),
        ),
    ]
